insert into cars (mark, model, engine, fuel, price, image) values ('Suzuki', 'Vitara', 'V8', 'elekter', 414, '/est/et/tempus/semper/est.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'Sienna', 'V12', 'gaas', 197, '/lobortis/vel/dapibus.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'T100 Xtra', 'V6', 'bensiin', 386, '/ullamcorper/augue/a.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'TundraMax', 'V8', 'elekter', 639, '/justo.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Grand Caravan', 'V10', 'elekter', 817, '/convallis/nunc/proin/at/turpis/a/pede.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'MX-5', 'V6', 'bensiin', 870, '/orci/luctus/et/ultrices/posuere/cubilia.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'Echo', 'V8', 'bensiin', 210, '/parturient/montes.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercury', 'Sable', 'V6', 'diisel', 162, '/in/tempus/sit.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Ramcharger', 'V8', 'elekter', 149, '/magna/vestibulum/aliquet/ultrices/erat.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Corvette', 'V10', 'bensiin', 427, '/enim/blandit/mi/in/porttitor/pede/justo.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Yukon XL 1500', 'V6', 'gaas', 148, '/molestie/sed/justo/pellentesque/viverra.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', 'Z3', 'V8', 'bensiin', 908, '/nulla/ac/enim.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'Mazda6', 'V10', 'gaas', 763, '/orci/luctus/et.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Aston Martin', 'DB9', 'V6', 'diisel', 888, '/ipsum/praesent/blandit/lacinia/erat/vestibulum.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Lotus', 'Esprit', 'V10', 'diisel', 543, '/ac/diam/cras/pellentesque/volutpat/dui/maecenas.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Montero', 'V8', 'gaas', 915, '/ultricies/eu.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Ram Van 3500', 'V6', 'gaas', 270, '/interdum/mauris/ullamcorper/purus.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Hyundai', 'Tiburon', 'V6', 'bensiin', 267, '/ornare/imperdiet/sapien.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', '4Runner', 'V12', 'elekter', 309, '/morbi/vel.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Chevette', 'V10', 'diisel', 493, '/tristique/est/et/tempus/semper/est.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Dynasty', 'V6', 'gaas', 542, '/at/feugiat.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Jaguar', 'XK Series', 'V12', 'diisel', 675, '/orci/nullam/molestie/nibh.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', '650', 'V10', 'diisel', 537, '/convallis/duis/consequat/dui/nec.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Express 2500', 'V8', 'diisel', 780, '/turpis/elementum/ligula/vehicula/consequat/morbi/a.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Dakota', 'V8', 'bensiin', 202, '/rutrum/ac/lobortis/vel.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'GTI', 'V8', 'diisel', 242, '/placerat/ante.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Volvo', 'XC90', 'V8', 'gaas', 606, '/felis/eu.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Kia', 'Sorento', 'V10', 'diisel', 232, '/dolor/sit/amet/consectetuer/adipiscing/elit.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Grand Am', 'V10', 'gaas', 474, '/pharetra/magna/ac/consequat/metus/sapien/ut.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Jeep', 'Liberty', 'V10', 'bensiin', 792, '/non/ligula/pellentesque.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercury', 'Milan', 'V10', 'bensiin', 826, '/maecenas/tincidunt/lacus/at.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Audi', '90', 'V12', 'bensiin', 421, '/integer/a/nibh/in/quis/justo/maecenas.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Porsche', 'Cayenne', 'V12', 'bensiin', 611, '/primis/in/faucibus/orci/luctus/et/ultrices.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Oldsmobile', '88', 'V8', 'elekter', 527, '/ut/dolor.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'Navajo', 'V8', 'bensiin', 265, '/sit/amet/nulla/quisque/arcu/libero.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Honda', 'S2000', 'V10', 'bensiin', 711, '/pede/malesuada/in.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Oldsmobile', 'Achieva', 'V6', 'gaas', 591, '/odio.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'Sunbird', 'V8', 'bensiin', 806, '/pellentesque/volutpat.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Honda', 'CR-V', 'V10', 'diisel', 212, '/accumsan.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Neon', 'V8', 'elekter', 123, '/sed/accumsan/felis/ut/at.json');
