services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cr
      MYSQL_USER: markus
      MYSQL_PASSWORD: markus
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/cars.sql:/docker-entrypoint-initdb.d/cars.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
